// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Skill struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	Category    string      `json:"category"`
	Proficiency pgtype.Int4 `json:"proficiency"`
}
