// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error)
	ListSkills(ctx context.Context) ([]Skill, error)
}

var _ Querier = (*Queries)(nil)
