// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skills.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (name, category, proficiency)
VALUES ($1, $2, $3)
RETURNING id, name, category, proficiency
`

type CreateSkillParams struct {
	Name        string      `json:"name"`
	Category    string      `json:"category"`
	Proficiency pgtype.Int4 `json:"proficiency"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill, arg.Name, arg.Category, arg.Proficiency)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Proficiency,
	)
	return i, err
}

const listSkills = `-- name: ListSkills :many
SELECT id, name, category, proficiency FROM skills ORDER BY category, name
`

func (q *Queries) ListSkills(ctx context.Context) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Proficiency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
