// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skills.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (name, category, proficiency, logo_url)
VALUES ($1, $2, $3, $4)
RETURNING id, name, category, proficiency, logo_url
`

type CreateSkillParams struct {
	Name        string      `json:"name"`
	Category    string      `json:"category"`
	Proficiency pgtype.Int4 `json:"proficiency"`
	LogoUrl     pgtype.Text `json:"logo_url"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill,
		arg.Name,
		arg.Category,
		arg.Proficiency,
		arg.LogoUrl,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Proficiency,
		&i.LogoUrl,
	)
	return i, err
}

const getSkillByName = `-- name: GetSkillByName :one
SELECT id, name, category, proficiency, logo_url FROM skills WHERE name = $1
`

func (q *Queries) GetSkillByName(ctx context.Context, name string) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkillByName, name)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Proficiency,
		&i.LogoUrl,
	)
	return i, err
}

const listSkills = `-- name: ListSkills :many
SELECT id, name, category, proficiency, logo_url FROM skills ORDER BY category, name
`

func (q *Queries) ListSkills(ctx context.Context) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Proficiency,
			&i.LogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSkill = `-- name: UpdateSkill :one
UPDATE skills SET category = $2, proficiency = $3, logo_url = $4, updated_at = NOW()
WHERE id = $1 RETURNING id, name, category, proficiency, logo_url
`

type UpdateSkillParams struct {
	ID          int32       `json:"id"`
	Category    string      `json:"category"`
	Proficiency pgtype.Int4 `json:"proficiency"`
	LogoUrl     pgtype.Text `json:"logo_url"`
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, updateSkill,
		arg.ID,
		arg.Category,
		arg.Proficiency,
		arg.LogoUrl,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Proficiency,
		&i.LogoUrl,
	)
	return i, err
}
